unstable_features = true
reorder_imports = true
force_multiline_blocks = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
control_brace_style = "ClosingNextLine"
max_width = 1000
tab_spaces = 4
hard_tabs = true
imports_layout = "Horizontal"
reorder_impl_items = true
group_imports = "StdExternalCrate"
